version: '3.1'
services:
  nginx:
    image: nginx
    container_name: akiira
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./dist/akira/browser/:/usr/share/nginx/html